### ISSUE TITLE
pass request body to erlang/elixir

### ISSUE THREAD

**Issue by xrzhao** [rusterlium/hyper#3]
Hyperbeam can be great to offload heavy data workload from erlang/elixir server,  and only proxying/forwarding control requests upward.  Because still not so family with rust language, I cannot figure out the way to pass request body to erlang/elixir (native/hyperbeam/src/server.rs), can you give some help, thanks a lot.

**Comment by scrogson** [comment]
Hi @xrzhao, thank you for your interest in this project. The current state of this project is not intended to be used by anyone at this point. I hope to spend more time on it in the coming weeks as we make improvements in `rustler` itself.

The server currently does not send the body into the BEAM, but I certainly intend on making that possible in the next round of work.
